<a href="https://colab.research.google.com/github/Shisiajoy/PYTHON-DATA-ANALYSIS/blob/main/Numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

creating a null vector of size 10

In [2]:
null_vector = np.zeros(10)
print(f"Null vector of size 10: {null_vector}")



Null vector of size 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


finding memory size of an array


In [3]:
print(f"Memory size of the null vector: {null_vector.nbytes} bytes")


Memory size of the null vector: 80 bytes


creat a null vector of size 10 and 1 as fifth value

In [4]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(f"Null vector of size 10 with the fifth value as 1: {null_vector}")


Null vector of size 10 with the fifth value as 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


creat a vector ranging from 10 to 49

In [5]:
vector = np.arange(10, 50)
print(f"Vector with values ranging from 10 to 49: {vector}")


Vector with values ranging from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


reverse a vector (first element becomes first)

In [6]:
reversed_vector = vector[::-1]
print(f"Reversed vector: {reversed_vector}")


Reversed vector: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


3 x 3 matrix ranging from 0 to 8

In [7]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(f"3x3 matrix with values ranging from 0 to 8:\n{matrix_3x3}")


3x3 matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Indices of Non-Zero Elements from [1, 2, 0, 0, 4, 0]

In [8]:
my_list = [1, 2, 0, 0, 4, 0]
non_zero_indices = np.nonzero(my_list)
print(f"Indices of non-zero elements: {non_zero_indices[0]}")


Indices of non-zero elements: [0 1 4]


a 3x3x3 Array with Random Values

In [9]:
random_3d_array = np.random.random((3, 3, 3))
print(f"3x3x3 array with random values:\n{random_3d_array}")


3x3x3 array with random values:
[[[0.22995643 0.72606337 0.89394901]
  [0.49352411 0.21870061 0.97023324]
  [0.52898839 0.39471952 0.77306278]]

 [[0.47627283 0.29892057 0.43743617]
  [0.42007257 0.88878359 0.58327555]
  [0.73771976 0.7214812  0.37118023]]

 [[0.49302933 0.18690506 0.70522386]
  [0.6539208  0.58788158 0.92261886]
  [0.31010229 0.19170296 0.52259676]]]


a 10x10 Array with Random Values and Find the Minimum and Maximum Values

In [10]:
random_10x10_array = np.random.random((10, 10))
min_value = np.min(random_10x10_array)
max_value = np.max(random_10x10_array)
print(f"10x10 array with random values:\n{random_10x10_array}")
print(f"Minimum value: {min_value:.4f}")
print(f"Maximum value: {max_value:.4f}")


10x10 array with random values:
[[0.71105222 0.85750211 0.23129222 0.7579419  0.79417956 0.61571125
  0.24322934 0.79746574 0.0974173  0.20940324]
 [0.91894641 0.75117248 0.90899716 0.69061607 0.38476895 0.31614399
  0.42134233 0.3106013  0.53996724 0.25833943]
 [0.21440659 0.90151774 0.84919884 0.86098087 0.63468162 0.44229314
  0.2034966  0.8538552  0.02842312 0.62434025]
 [0.02153188 0.05637807 0.93433203 0.98431386 0.57358564 0.94899003
  0.97096128 0.13637818 0.11885048 0.66362784]
 [0.93251191 0.04432038 0.9105385  0.24254188 0.46059665 0.18686079
  0.78732016 0.7391348  0.86714681 0.99779788]
 [0.88264303 0.33354109 0.31900246 0.50807889 0.07380833 0.25459462
  0.49032356 0.30516051 0.56257552 0.6439041 ]
 [0.68611871 0.95019541 0.08029435 0.1372997  0.87335799 0.37525288
  0.09493049 0.10219319 0.47873015 0.29414603]
 [0.54563163 0.1638961  0.97013478 0.92142709 0.3274749  0.83120283
  0.62942841 0.06052423 0.16991912 0.88380325]
 [0.36561968 0.14939542 0.56407935 0.23059791 0.