<a href="https://colab.research.google.com/github/Shisiajoy/PYTHON-DATA-ANALYSIS/blob/main/Numpy02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

How to add a border (filled with 0's) around an existing array?

In [1]:
import numpy as np

existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

rows, cols = existing_array.shape

# Create a new array with the desired shape (adding 2 to each dimension for the border)
new_array = np.zeros((rows + 2, cols + 2), dtype=existing_array.dtype)

# Copy the existing array into the center of the new array
new_array[1:-1, 1:-1] = existing_array

print(new_array)


[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


Results of the following

In [2]:
0 * np.nan

nan

In [3]:
np.nan == np.nan

False

In [4]:
np.inf > np.nan

False

In [5]:

np.nan - np.nan

nan

In [6]:
np.nan in set([np.nan])

True

In [7]:
0.3 == 3 * 0.1

False

In [8]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8))

for i in range(8):
    for j in range(8):
        # If the sum of row index and column index is even, fill with 1
        if (i + j) % 2 == 0:
            matrix[i][j] = 1

print(matrix)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [1]:
import numpy as np

# Create a (6, 7, 8) shape array
array_shape = (6, 7, 8)
total_elements = np.prod(array_shape)

element_index = 99

# Calculate the (x, y, z) indices
z_index, remainder = divmod(element_index, array_shape[2])
y_index, x_index = divmod(remainder, array_shape[1])

print(f"The index (x, y, z) of the 100th element is ({x_index}, {y_index}, {z_index}).")


The index (x, y, z) of the 100th element is (3, 0, 12).


Create a checkerboard 8x8 matrix using the tile function