<a href="https://colab.research.google.com/github/Shisiajoy/PYTHON-DATA-ANALYSIS/blob/main/Numpy02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

How to add a border (filled with 0's) around an existing array?

In [1]:
import numpy as np

existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

rows, cols = existing_array.shape

# Create a new array with the desired shape (adding 2 to each dimension for the border)
new_array = np.zeros((rows + 2, cols + 2), dtype=existing_array.dtype)

# Copy the existing array into the center of the new array
new_array[1:-1, 1:-1] = existing_array

print(new_array)


[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


Results of the following

In [2]:
0 * np.nan

nan

In [3]:
np.nan == np.nan

False

In [4]:
np.inf > np.nan

False

In [5]:

np.nan - np.nan

nan

In [6]:
np.nan in set([np.nan])

True

In [7]:
0.3 == 3 * 0.1

False

In [8]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8))

for i in range(8):
    for j in range(8):
        # If the sum of row index and column index is even, fill with 1
        if (i + j) % 2 == 0:
            matrix[i][j] = 1

print(matrix)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [1]:
import numpy as np

# Create a (6, 7, 8) shape array
array_shape = (6, 7, 8)
total_elements = np.prod(array_shape)

element_index = 99

# Calculate the (x, y, z) indices
z_index, remainder = divmod(element_index, array_shape[2])
y_index, x_index = divmod(remainder, array_shape[1])

print(f"The index (x, y, z) of the 100th element is ({x_index}, {y_index}, {z_index}).")


The index (x, y, z) of the 100th element is (3, 0, 12).


Create a checkerboard 8x8 matrix using the tile function

In [2]:
import numpy as np

# Create a 2x2 checkerboard pattern
checkerboard_tile = np.array([[0, 1], [1, 0]])

# Create an 8x8 checkerboard matrix by tiling the 2x2 pattern
checkerboard_matrix = np.tile(checkerboard_tile, (4, 4))

print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix by dividing each element by the sum of all elements
normalized_matrix = random_matrix / np.sum(random_matrix)

# Print the original and normalized matrices
print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.03704438 0.08841753 0.34207548 0.2838593  0.36007813]
 [0.46435715 0.43829493 0.90453099 0.65922248 0.38853685]
 [0.01050633 0.6832006  0.93400744 0.86893588 0.86316612]
 [0.39952035 0.43639761 0.06976933 0.19453553 0.81664794]
 [0.57277139 0.13102133 0.83033948 0.48712426 0.33450999]]

Normalized Matrix:
[[0.00319379 0.00762294 0.02949214 0.02447301 0.03104424]
 [0.04003469 0.03778772 0.0779844  0.05683506 0.03349782]
 [0.00090581 0.05890234 0.08052572 0.07491556 0.07441812]
 [0.03444476 0.03762415 0.00601518 0.01677194 0.07040754]
 [0.04938165 0.01129604 0.07158796 0.04199756 0.02883988]]


 Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [4]:
import numpy as np

# Define custom dtype for RGBA color
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Example RGBA color values
red = (255, 0, 0, 255)
green = (0, 255, 0, 255)
blue = (0, 0, 255, 255)

# Create arrays of custom dtype
red_color = np.array(red, dtype=color_dtype)
green_color = np.array(green, dtype=color_dtype)
blue_color = np.array(blue, dtype=color_dtype)

print("Red color (RGBA):", red_color)
print("Green color (RGBA):", green_color)
print("Blue color (RGBA):", blue_color)


Red color (RGBA): (255, 0, 0, 255)
Green color (RGBA): (0, 255, 0, 255)
Blue color (RGBA): (0, 0, 255, 255)


Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [6]:
import numpy as np

# Create a 5x3 matrix
matrix_a = np.random.rand(5, 3)

# Create a 3x2 matrix
matrix_b = np.random.rand(3, 2)

# Multiply the matrices (real matrix product)
result_matrix = np.dot(matrix_a, matrix_b)

# Print the result
print("Matrix A (5x3):")
print(matrix_a)
print("\nMatrix B (3x2):")
print(matrix_b)
print("\nResult Matrix (5x2):")
print(result_matrix)


Matrix A (5x3):
[[0.46228444 0.15870012 0.38565156]
 [0.84318321 0.91811633 0.12062618]
 [0.1524753  0.23621475 0.9495606 ]
 [0.9194146  0.2711134  0.12819473]
 [0.7666195  0.19532723 0.16767927]]

Matrix B (3x2):
[[0.8037118  0.5088584 ]
 [0.20842748 0.5721792 ]
 [0.7307525  0.48120294]]

Result Matrix (5x2):
[[0.68643676 0.51161889]
 [0.95718484 1.01243361]
 [0.86567363 0.66967686]
 [0.88913046 0.68466498]
 [0.77938475 0.58255071]]


Given a 1D array, negate all elements which are between 3 and 8, in place.

In [7]:
import numpy as np

# Create a 1D array
arr = np.array([1, 4, 6, 3, 9, 2, 7, 5, 8])

# Negate elements between 3 and 8 (inclusive) in place
arr[(arr >= 3) & (arr <= 8)] *= -1

# Print the modified array
print("Modified Array:")
print(arr)


Modified Array:
[ 1 -4 -6 -3  9  2 -7 -5 -8]


whats the output

In [8]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


 Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
**bold text**

 What are the result of the following expressions?


In [11]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-11-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-11-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-11-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

How to round away from zero a float array ?

In [12]:
import numpy as np

# Create a float array
float_array = np.array([-2.3, 1.5, -0.7, 3.2, -4.8])

# Round away from zero (towards positive infinity)
rounded_array = np.ceil(float_array)

# Print the original and rounded arrays
print("Original Float Array:")
print(float_array)
print("\nRounded Array (away from zero):")
print(rounded_array)


Original Float Array:
[-2.3  1.5 -0.7  3.2 -4.8]

Rounded Array (away from zero):
[-2.  2. -0.  4. -4.]


 How to find common values between two arrays?

In [13]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 5, 7, 9])

common_elements = np.intersect1d(array1, array2)
print(common_elements)


[3 5]
