<a href="https://colab.research.google.com/github/Shisiajoy/PYTHON-DATA-ANALYSIS/blob/main/Numpy03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How to ignore all numpy warnings (not recommended)?

In [1]:
import numpy as np

# Ignore all NumPy warnings
np.seterr(all="ignore")

# Example usage (suppressing division by zero warning)
array1 = np.array([1.0, 2.0, 3.0])
array2 = np.array([0.0, 0.0, 0.0])

result = array1 / array2
print("Result (division by zero suppressed):", result)


Result (division by zero suppressed): [inf inf inf]


Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

In [2]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

How to get the dates of yesterday, today and tomorrow?

In [3]:
import datetime

# Get today's date
today = datetime.date.today()

# Get yesterday's date
yesterday = today - datetime.timedelta(days=1)

# Get tomorrow's date
tomorrow = today + datetime.timedelta(days=1)

# Print the dates
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-03-25
Today: 2024-03-26
Tomorrow: 2024-03-27


 How to get all the dates corresponding to the month of July 2016?

In [4]:
import numpy as np

# Get all dates for July 2016
dates_july_2016 = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

# Print the dates
print("Dates for July 2016:")
print(dates_july_2016)


Dates for July 2016:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


How to compute ((A+B)*(-A/2)) in place (without copy)?

In [6]:
import numpy as np

# Create arrays A and B
A = np.array([1, 2, 3], dtype=np.float64)  # Convert A to float64
B = np.array([4, 5, 6])

# Compute ((A+B)*(-A/2)) in place
result = (A + B) * (-A / 2)

# Print the result
print("Result (corrected):", result)


Result (corrected): [ -2.5  -7.  -13.5]


 Extract the integer part of a random array of positive numbers using 4 different methods



  ***Method 1: Using np.floor()***



In [7]:
import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 10  # Scale to positive range

# Extract integer part using np.floor()
integer_part_floor = np.floor(random_array)

print("Integer Part (Method 1 - np.floor()):")
print(integer_part_floor)


Integer Part (Method 1 - np.floor()):
[2. 4. 3. 8. 2.]


 ***Method 2: Using np.trunc()***

In [8]:
# Extract integer part using np.trunc()
integer_part_trunc = np.trunc(random_array)

print("Integer Part (Method 2 - np.trunc()):")
print(integer_part_trunc)


Integer Part (Method 2 - np.trunc()):
[2. 4. 3. 8. 2.]


***Method 3: Using astype(int)***




In [9]:
# Extract integer part using np.astype(int)
integer_part_cast = random_array.astype(int)

print("Integer Part (Method 3 - np.astype(int)):")
print(integer_part_cast)


Integer Part (Method 3 - np.astype(int)):
[2 4 3 8 2]


***Method 4: Using np.around(decimals=0)***

In [10]:
# Extract integer part using np.around(decimals=0)
integer_part_round = np.around(random_array, decimals=0)

print("Integer Part (Method 4 - np.around(decimals=0)):")
print(integer_part_round)


Integer Part (Method 4 - np.around(decimals=0)):
[2. 4. 4. 8. 3.]


Create a 5x5 matrix with row values ranging from 0 to 4

In [11]:
import numpy as np

# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.tile(np.arange(5), (5, 1))

# Print the matrix
print("5x5 Matrix:")
print(matrix)


5x5 Matrix:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


Consider a generator function that generates 10 integers and use it to build an array

In [12]:
import numpy as np

# Define a generator function that yields 10 integers
def generate_integers():
    for i in range(10):
        yield i

# Create an array from the generator function
array_from_generator = np.fromiter(generate_integers(), dtype=int)

# Print the array
print("Array from Generator Function:")
print(array_from_generator)


Array from Generator Function:
[0 1 2 3 4 5 6 7 8 9]


 Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [13]:
import numpy as np

# Create a vector of size 10 with values ranging from 0 to 1 (both excluded)
vector = np.linspace(0, 1, num=10, endpoint=False)

# Print the vector
print("Vector with values ranging from 0 to 1 (both excluded):")
print(vector)


Vector with values ranging from 0 to 1 (both excluded):
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


 Create a random vector of size 10 and sort it

In [14]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the vector in ascending order
sorted_vector = np.sort(random_vector)

# Print the sorted vector
print("Sorted Vector:")
print(sorted_vector)


Sorted Vector:
[0.08510997 0.19604658 0.37585909 0.40917408 0.43784314 0.50431195
 0.53538419 0.57153754 0.73769341 0.74221493]


How to sum a small array faster than np.sum?

In [15]:
import numpy as np

# Create a small array
small_array = np.array([1, 2, 3, 4, 5])

# Sum using Python's built-in sum() function
result = sum(small_array)

print("Sum using sum():", result)


Sum using sum(): 15


Consider two random array A and B, check if they are equal

In [16]:
import numpy as np

# Create two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


 Make an array immutable (read-only)

In [17]:
import numpy as np

# Create a mutable (writable) array
mutable_array = np.array([1, 2, 3, 4, 5])

# Make the array read-only (immutable)
immutable_array = np.array(mutable_array, copy=False)

# Try to modify the immutable array (should raise an error)
try:
    immutable_array[0] = 10
except ValueError:
    print("Error: Cannot modify the immutable array.")

# Print the original mutable array and the immutable array
print("Mutable Array (original):", mutable_array)
print("Immutable Array:", immutable_array)


Mutable Array (original): [10  2  3  4  5]
Immutable Array: [10  2  3  4  5]


Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [18]:
import numpy as np

# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_matrix = np.random.rand(10, 2)

# Convert Cartesian coordinates to polar coordinates
def cartesian_to_polar(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)  # Returns angle in radians
    return rho, phi

# Apply the conversion to each row in the matrix
polar_matrix = np.apply_along_axis(lambda row: cartesian_to_polar(row[0], row[1]), axis=1, arr=cartesian_matrix)

# Print the original Cartesian matrix and the polar matrix
print("Cartesian Coordinates (10x2 matrix):")
print(cartesian_matrix)
print("\nPolar Coordinates (rho, phi):")
print(polar_matrix)


Cartesian Coordinates (10x2 matrix):
[[0.4320724  0.34696095]
 [0.9798421  0.83626772]
 [0.6966714  0.82073338]
 [0.98671803 0.44842736]
 [0.82614052 0.43105297]
 [0.14154379 0.75651215]
 [0.59408477 0.48924377]
 [0.8089608  0.06222559]
 [0.25525362 0.69114082]
 [0.76275576 0.63982395]]

Polar Coordinates (rho, phi):
[[0.55413758 0.67657713]
 [1.2881903  0.70650624]
 [1.07654741 0.86697603]
 [1.08383558 0.42655959]
 [0.93183412 0.48090929]
 [0.76963971 1.38583436]
 [0.76960781 0.68892187]
 [0.81135047 0.07676924]
 [0.73677    1.21701275]
 [0.99557574 0.69797464]]


 Create random vector of size 10 and replace the maximum value by 0

In [19]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the maximum value in the vector
max_value = np.max(random_vector)

# Replace the maximum value with 0
random_vector[random_vector == max_value] = 0

# Print the modified vector
print("Random Vector with Maximum Value Replaced:")
print(random_vector)


Random Vector with Maximum Value Replaced:
[0.05807231 0.58229962 0.69145723 0.70807804 0.10010377 0.72241368
 0.85150233 0.         0.48564594 0.85497049]
